from __future__ import annotations

from dataclasses import asdict, dataclass

from .config import CameraConfig


@dataclass(frozen=True)
class MatterCameraCapability:
    name: str
    status: str
    bridge_endpoint: str
    notes: str


def camera_capabilities(camera: CameraConfig) -> dict[str, object]:
    """Return the Matter 1.5.1-facing feature contract for one camera.

    This is intentionally explicit: it lets tests and users see which parts are
    backed by real RTSP/ONVIF behavior today and which are advertised as bridge
    placeholders for a future certified Matter stack.
    """
    audio_status = "enabled" if camera.matter.advertise_audio else "disabled"
    ptz_status = "enabled" if camera.matter.advertise_ptz else "disabled"
    two_way_status = "enabled" if camera.matter.advertise_two_way_audio else "disabled"
    recording_status = "enabled" if camera.matter.advertise_recording else "disabled"

    capabilities = [
        MatterCameraCapability(
            "live_video",
            "enabled",
            f"/cameras/{camera.id}/probe",
            "RTSP input is probed with ffprobe and can be relayed by go2rtc/ffmpeg.",
        ),
        MatterCameraCapability(
            "live_audio",
            audio_status,
            f"/cameras/{camera.id}/probe",
            "Advertised when the camera stream exposes an audio track.",
        ),
        MatterCameraCapability(
            "two_way_audio",
            two_way_status,
            f"/cameras/{camera.id}/audio/talkback",
            "Matter 1.5 camera feature; disabled until a camera talkback path is configured.",
        ),
        MatterCameraCapability(
            "multi_stream",
            "enabled",
            f"/cameras/{camera.id}/streams",
            "Matter 1.5.1-aligned high/mobile/analysis profiles backed by the RTSP source.",
        ),
        MatterCameraCapability(
            "hls",
            "enabled",
            f"/cameras/{camera.id}/streams/{{profile}}/hls",
            "Matter 1.5.1 media format generated by the bridge ffmpeg relay.",
        ),
        MatterCameraCapability(
            "dash",
            "enabled",
            f"/cameras/{camera.id}/streams/{{profile}}/dash",
            "Matter 1.5.1 media format generated by the bridge ffmpeg relay.",
        ),
        MatterCameraCapability(
            "snapshot_jpeg",
            "enabled",
            f"/cameras/{camera.id}/snapshot.jpg",
            "Single-frame capture with ffmpeg.",
        ),
        MatterCameraCapability(
            "snapshot_heic",
            "enabled",
            f"/cameras/{camera.id}/snapshot.heic",
            "Matter 1.5.1 image format encoded with heif-enc in the bridge container.",
        ),
        MatterCameraCapability(
            "ptz",
            ptz_status,
            f"/cameras/{camera.id}/ptz",
            "ONVIF PTZ status and continuous move controls.",
        ),
        MatterCameraCapability(
            "privacy_zones",
            "configurable",
            f"/cameras/{camera.id}/zones/privacy",
            "Bridge-side zone metadata for Matter controllers.",
        ),
        MatterCameraCapability(
            "detection_zones",
            "configurable",
            f"/cameras/{camera.id}/zones/detection",
            "Bridge-side zone metadata for events and analytics.",
        ),
        MatterCameraCapability(
            "recording",
            recording_status,
            f"/cameras/{camera.id}/recording",
            "Matter camera storage hooks; disabled unless a recorder target is configured.",
        ),
    ]

    return {
        "id": camera.id,
        "name": camera.name,
        "standard": camera.matter.standard,
        "device_type": camera.matter.device_type,
        "capabilities": [asdict(item) for item in capabilities],
    }


def stream_profiles(camera: CameraConfig) -> dict[str, object]:
    base = f"/cameras/{camera.id}/streams"
    return {
        "camera_id": camera.id,
        "profiles": [
            {
                "id": "high",
                "purpose": "recording",
                "source": camera.rtsp_url,
                "target": f"{base}/high",
                "notes": "Preserve source quality when possible.",
            },
            {
                "id": "mobile",
                "purpose": "live_view",
                "source": camera.rtsp_url,
                "target": f"{base}/mobile",
                "notes": "Transcode/downscale in production for low-bandwidth Matter clients.",
            },
            {
                "id": "analysis",
                "purpose": "ai_detection",
                "source": camera.rtsp_url,
                "target": f"{base}/analysis",
                "notes": "Lower frame rate profile for analytics consumers.",
            },
        ],
    }
